name: Build

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v2
      - name: install buildx
        id: buildx
        uses: crazy-max/ghaction-docker-buildx@v1
        with:
          version: latest
      - name: build the image
        run: |
          docker buildx build \
            --tag flomonster/flomonster.fr:latest \
            --platform linux/amd64,linux/arm64 .
